FROM sistemasoperativostur/router:2022-08-08--41-10 AS updates
LABEL mantainer=”ctaffer@unsl.edu.ar”
WORKDIR /root
RUN apt update
RUN apt install -y elinks curl smbclient cifs-utils bind9-host isc-dhcp-client
#crear archivo /etc/dhcp/dhclient-exit-hooks.d/mv
#crear archivo /etc/dhcp/dhclient-enter-hooks.d/mv
#permisos ejecucion, ambos contenidos
#    #!/bin/bash
#    ORIGEN=`ls -t /etc/resolv.conf* | head -n1`
#    cp $ORIGEN /etc/resolv.conf
#apt autoremove
#history -c
#
#FROM sistemasoperativostur/router:2022-08-08--41-10
#LABEL mantainer=”ctaffer@unsl.edu.ar”
#
#set root pass
RUN echo root:lpr | chpasswd
RUN apt autoremove
